/**
 * Created by Shreedhar Acharya
 * 14/02/2021
 */


/* Create customer table if already not exist */

CREATE TABLE IF NOT EXISTS users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  user_address JSON,
  user_email VARCHAR(320) NOT NULL,
  user_dob DATE NOT NULL,
  user_pass VARCHAR(255)
);

/* Create customer table if already not exist */

CREATE TABLE IF NOT EXISTS customers (
  cust_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  cust_name VARCHAR(100) NOT NULL,
  cust_phone TEXT [] NOT NULL,
  cust_address JSON,
  cust_email VARCHAR(320) NOT NULL,
  cust_company VARCHAR(100) NOT NULL,
  cust_dob DATE NOT NULL,
  cust_pass VARCHAR(255),
  user_id INT
);

/* Create user roles table if already not exist */

CREATE TABLE IF NOT EXISTS user_roles (
  user_id INT NOT NULL,
  role_id INT NOT NULL
);

/* Create supplier table if already not exist */

CREATE TABLE IF NOT EXISTS supplier (
  supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  supplier_name VARCHAR(100) NOT NULL,
  supplier_phone TEXT [] NOT NULL,
  supplier_address JSON,
  supplier_email VARCHAR(320) NOT NULL,
  supplier_company VARCHAR(100) NOT NULL,
  supplier_type VARCHAR(100) NOT NULL,
);

/* Create restaurant table if already not exist */

CREATE TABLE IF NOT EXISTS res_table (
  table_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  table_shape VARCHAR(100) NOT NULL,
  table_type VARCHAR(100) NOT NULL,
  table_cap INT NOT NULL,
  table_rate INT NOT NULL
);

/* Create order table if already not exist */

CREATE TABLE IF NOT EXISTS order (
  order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  cust_id INT NOT NULL,
  user_id INT NOT NULL,
  table_id INT NOT NULL,
);

/* Create item table if already not exist */

CREATE TABLE IF NOT EXISTS item (
  item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  item_name VARCHAR(100) NOT NULL,
  item_desc VARCHAR(200) NOT NULL,
  item_unit INT NOT NULL,
  item_stock INT NOT NULL
);

/* Create inventory table if already not exist */

CREATE TABLE IF NOT EXISTS inventory (
  invent_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  invent_name VARCHAR(100) NOT NULL,
  invent_desc VARCHAR(200) NOT NULL,
  invent_unit INT NOT NULL,
  invent_status boolean NOT NULL,
  invent_stock INT NOT NULL,
  invent_mfd DATE NOT NULL,
  invent_exp DATE NOT NULL,
);

/* Create feedback table if already not exist */

CREATE TABLE IF NOT EXISTS feedback (
  feedback_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  cust_id INT NOT NULL,
  feedback_msg VARCHAR(300) NOT NULL,
  feedback_sub VARCHAR(100) ,
  feedback_date DATE NOT NULL,
);

/* Create courier table if already not exist */

CREATE TABLE IF NOT EXISTS courier (
  courier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  courier_name VARCHAR(100) NOT NULL,
  courier_comp VARCHAR(100) NOT NULL,
  courier_phone TEXT [] NOT NULL,
  courier_address JSON,

);

/* Create purchase table if already not exist */

CREATE TABLE IF NOT EXISTS purchase (
  purchase_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  invoice_no INT NOT NULL,
  supplier_id INT NOT NULL,
  purchase_date DATE NOT NULL,

);

/* Create special_menu table if already not exist */

CREATE TABLE IF NOT EXISTS special_menu (
  item_id INT NOT NULL,
  offer_id INT NOT NULL,
  offer_item VARCHAR(100) NOT NULL,
  smenu_date DATE NOT NULL,

);

/* Create ordered item table if already not exist */

CREATE TABLE IF NOT EXISTS ordered_item (
  ordered_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  item_id INT NOT NULL,
  ordered_qty INT NOT NULL,
);

/* Create item category table if already not exist */

CREATE TABLE IF NOT EXISTS item_category (
  cat_id INT NOT NULL,
  parent_cat_id INT NOT NULL,
  cat_name VARCHAR(100) NOT NULL,
);

/* Create unit price  table if already not exist */

CREATE TABLE IF NOT EXISTS unit_price (
  item_id INT NOT NULL,
  price INT NOT NULL,
  unit VARCHAR(100) NOT NULL,
);

/* Create purchased_items table if already not exist */

CREATE TABLE IF NOT EXISTS purchased_items (
  purchase_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  invent_id INT NOT NULL,
  qty INT NOT NULL,
);


/* Create roles table if already not exist */

CREATE TABLE IF NOT EXISTS roles (
  role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  role_name VARCHAR(100)
);

/* Create table_reservation table if already not exist */

CREATE TABLE IF NOT EXISTS table_reservation (
  table_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id INT NOT NULL,
  cust_id INT NOT NULL,
  start_time DATE NOT NULL,
  end_time DATE NOT NULL,
  cust_count INT NOT NULL,
);

/* Create discount table if already not exist */

CREATE TABLE IF NOT EXISTS discount (
  disc_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  disc_amt INT NOT NULL,
  disc_type VARCHAR(100),
);

/* Create offer table if already not exist */

CREATE TABLE IF NOT EXISTS offer (
  offer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  offer_type VARCHAR(100) NOT NULL,
  item_id INT NOT NULL,
  offer_start DATE NOT NULL,
  offer_end DATE NOT NULL,
);

/* Create inventory category table if already not exist */

CREATE TABLE IF NOT EXISTS inventory_category (
  invent_cat_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  invent_cat_name VARCHAR(100) NOT NULL,
  purchase_id INT NOT NULL,
);

/* Create restaurant table if already not exist */

CREATE TABLE IF NOT EXISTS supplier_inventory (
    sup_invent_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    invent_cat_id INT NOT NULL,
    supplier_id INT NOT NULL,
);

/* Create offered items table if already not exist */

CREATE TABLE IF NOT EXISTS offered_items(
    offer_id INT NOT NULL,
    item VARCHAR(100) NOT NULL,
);




